//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuClass.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public int BlockID { get; set; }
        public Nullable<int> BlockerUser { get; set; }
        public Nullable<int> BlockedUser { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    
        public virtual User UsersAreBlocker { get; set; }
        public virtual User UsersAreBlocked { get; set; }
    }
}
