//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuClass.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow
    {
        public int FollowID { get; set; }
        public Nullable<int> FollowerID { get; set; }
        public Nullable<int> FollowedID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual User UsersFollower { get; set; }
        public virtual User UsersFollowed { get; set; }
    }
}
