//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuClass.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonCommentLike
    {
        public int LessonCommentLikeID { get; set; }
        public Nullable<int> LessonCommentID { get; set; }
        public Nullable<int> LikedUserID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    
        public virtual LessonComment LessonComment { get; set; }
        public virtual User User { get; set; }
    }
}
