//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuClass.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LessonComment()
        {
            this.LessonCommentLikes = new HashSet<LessonCommentLike>();
            this.Reports = new HashSet<Report>();
        }
    
        public int LessonCommentID { get; set; }
        public Nullable<int> LessonContentID { get; set; }
        public Nullable<int> AddedUserID { get; set; }
        public string LessonCommentText { get; set; }
        public Nullable<int> LessonCommentFileID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonCommentLike> LessonCommentLikes { get; set; }
        public virtual LessonContent LessonContent { get; set; }
        public virtual User User { get; set; }
        public virtual UserFile UserFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
