//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuClass.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonAccess
    {
        public int LessonAccessID { get; set; }
        public int LessonID { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Lesson Lesson { get; set; }
    }
}
