//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuClass.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public Nullable<int> ReporterID { get; set; }
        public Nullable<int> ReportedContentID { get; set; }
        public Nullable<int> ReportedCommendID { get; set; }
        public Nullable<int> ReportedUserID { get; set; }
        public string ReportContent { get; set; }
        public Nullable<int> ReportTypeID { get; set; }
        public Nullable<bool> IsCheckedReport { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
    
        public virtual LessonComment LessonComment { get; set; }
        public virtual LessonContent LessonContent { get; set; }
        public virtual ReportType ReportType { get; set; }
        public virtual User UsersAreReporter { get; set; }
        public virtual User UsersAreReported { get; set; }
    }
}
