//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBUserFollows
    {
        public int ID { get; set; }
        public Nullable<int> FollowingUserID { get; set; }
        public Nullable<int> FollowedUserID { get; set; }
    
        public virtual DBUsers DBUsers { get; set; }
        public virtual DBUsers DBUsers1 { get; set; }
    }
}
